### ISSUE TITLE
Illegible collapsed text

### ISSUE THREAD

**Issue by lebigot** [simicd/jupyterlab-tailwind-theme#42]
In the dark mode, the text describing the contents of a collapsed section ("+ 20 cells hidden") is not legible: it's in a light script over a light background (Chrome, macOS). Here is what it looks like on my machine:

<img width="220" alt="Screen Shot 2021-08-23 at 22 06 54" src="https://user-images.githubusercontent.com/5793/130512533-3bbc5138-6350-4b12-b530-e66aad201046.png">

Hovering over the collapsed box correctly shows a light text over a dark grey background.

**Comment by catethos** [comment]
I am not sure how where the theme saves the css file, so I just use a chrome extension Stylebot to change it
![image](https://user-images.githubusercontent.com/6882603/147872991-cbfc3b54-c626-49be-831a-67208c7cfd8c.png)

The required changed in `css` the `backgroud-color` and color under the selector `.jp-showHiddenCellsButton`
```css
.jp-showHiddenCellsButton {
    margin-left: calc(var(--jp-cell-prompt-width) + 2 * var(--jp-code-padding));
    margin-top: var(--jp-code-padding);
    border: 1px solid var(--jp-border-color2);
    background-color: #2D3748 !important;
    color: #9A9FA7 !important;
}
```
